export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_GALERY_FOR_AGENT_AND_CUSTOMER_REQUEST = "PRODUCT_GALERY_FOR_AGENT_AND_CUSTOMER_REQUEST";
export const PRODUCT_GALERY_FOR_AGENT_AND_CUSTOMER_SUCCESS = "PRODUCT_GALERY_FOR_AGENT_AND_CUSTOMER_SUCCESS";
export const PRODUCT_GALERY_FOR_AGENT_AND_CUSTOMER_FAIL = "PRODUCT_GALERY_FOR_AGENT_AND_CUSTOMER_FAIL";


export const PRODUCT_LIST_PRODUCTTYPE_CATEGORY_AGENT_REQUEST = "PRODUCT_LIST_PRODUCTTYPE_CATEGORY_AGENT_REQUEST";
export const PRODUCT_LIST_PRODUCTTYPE_CATEGORY_AGENT_SUCCESS = "PRODUCT_LIST_PRODUCTTYPE_CATEGORY_AGENT_SUCCESS";
export const PRODUCT_LIST_PRODUCTTYPE_CATEGORY_AGENT_FAIL = "PRODUCT_LIST_PRODUCTTYPE_CATEGORY_AGENT_FAIL";

export const PRODUCT_LIST_FOR_APPSHARER_AND_SHOPER_REQUEST = "PRODUCT_LIST_FOR_APPSHARER_AND_SHOPER_REQUEST";
export const PRODUCT_LIST_FOR_APPSHARER_AND_SHOPER_SUCCESS = "PRODUCT_LIST_FOR_APPSHARER_AND_SHOPER_SUCCESS";
export const PRODUCT_LIST_FOR_APPSHARER_AND_SHOPER_FAIL = "PRODUCT_LIST_FOR_APPSHARER_AND_SHOPER_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_SAVE_REQUEST = "PRODUCT_SAVE_REQUEST";
export const PRODUCT_SAVE_SUCCESS = "PRODUCT_SAVE_SUCCESS";
export const PRODUCT_SAVE_FAIL = "PRODUCT_SAVE_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_DELETE_AGENT_REQUEST = "PRODUCT_DELETE_AGENT_REQUEST";
export const PRODUCT_DELETE_AGENT_SUCCESS = "PRODUCT_DELETE_AGENT_SUCCESS";
export const PRODUCT_DELETE_AGENT_FAIL = "PRODUCT_DELETE_AGENT_FAIL";


