export const PRODUCTTYPE_LIST_REQUEST = "PRODUCTTYPE_LIST_REQUEST";
export const PRODUCTTYPE_LIST_SUCCESS = "PRODUCTTYPE_LIST_SUCCESS";
export const PRODUCTTYPE_LIST_FAIL = "PRODUCTTYPE_LIST_FAIL";

export const PRODUCTTYPE_DETAILS_REQUEST = "PRODUCTTYPE_DETAILS_REQUEST";
export const PRODUCTTYPE_DETAILS_SUCCESS = "PRODUCTTYPE_DETAILS_SUCCESS";
export const PRODUCTTYPE_DETAILS_FAIL = "PRODUCTTYPE_DETAILS_FAIL";

export const PRODUCTTYPE_SAVE_REQUEST = "PRODUCTTYPE_SAVE_REQUEST";
export const PRODUCTTYPE_SAVE_SUCCESS = "PRODUCTTYPE_SAVE_SUCCESS";
export const PRODUCTTYPE_SAVE_FAIL = "PRODUCTTYPE_SAVE_FAIL";

export const PRODUCTTYPE_UPDATE_REQUEST = "PRODUCTTYPE_UPDATE_REQUEST";
export const PRODUCTTYPE_UPDATE_SUCCESS = "PRODUCTTYPE_UPDATE_SUCCESS";
export const PRODUCTTYPE_UPDATE_FAIL = "PRODUCTTYPE_UPDATE_FAIL";

export const PRODUCTTYPE_DELETE_REQUEST = "PRODUCTTYPE_DELETE_REQUEST";
export const PRODUCTTYPE_DELETE_SUCCESS = "PRODUCTTYPE_DELETE_SUCCESS";
export const PRODUCTTYPE_DELETE_FAIL = "PRODUCTTYPE_DELETE_FAIL";


