export const ADMIN_PROFILE_UPDATE_REQUEST = 'ADMIN_PROFILE_UPDATE_REQUEST';
export const ADMIN_PROFILE_UPDATE_SUCCESS = 'ADMIN_aPROFILE_UPDATE_SUCCESS';
export const ADMIN_PROFILE_UPDATE_FAIL = 'ADMIN_PROFILE_UPDATE_FAIL';

export const ADMIN_PROFILE_DETAILS_REQUEST = 'ADMIN_PROFILE_DETAILS_REQUEST';
export const ADMIN_PROFILE_DETAILS_SUCCESS = 'ADMIN_PROFILE_DETAILS_SUCCESS';
export const ADMIN_PROFILE_DETAILS_FAIL = 'ADMIN_PROFILE_DETAILS_FAIL';

export const ADMIN_PASSWORD_UPDATE_REQUEST = 'ADMIN_PASSWORD_UPDATE_REQUEST';
export const ADMIN_PASSWORD_UPDATE_SUCCESS = 'ADMIN_PASSWORD_UPDATE_SUCCESS';
export const ADMIN_PASSWORD_UPDATE_FAIL = 'ADMIN_PASSWORD_UPDATE_FAIL';

export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST';
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';