export const AGENT_LIST_REQUEST = "AGENT_LIST_REQUEST"
export const AGENT_LIST_SUCCESS = "AGENT_LIST_SUCCESS"
export const AGENT_LIST_FAIL = "AGENT_LIST_FAIL"

export const AGENT_PROFILE_UPDATE_REQUEST = "AGENT_PROFILE_UPDATE_REQUEST";
export const AGENT_PROFILE_UPDATE_SUCCESS = "AGENT_PROFILE_UPDATE_SUCCESS";
export const AGENT_PROFILE_UPDATE_FAIL = "AGENT_PROFILE_UPDATE_FAIL";

export const FIND_AGENT_REQUEST = "FIND_AGENT_REQUEST";
export const FIND_AGENT_SUCCESS = "FIND_AGENT_SUCCESS";
export const FIND_AGENT_FAIL = "FIND_AGENT_FAIL";

export const AGENT_PROFILE_DETAILS_REQUEST = 'AGENT_PROFILE_DETAILS_REQUEST';
export const AGENT_PROFILE_DETAILS_SUCCESS = 'AGENT_PROFILE_DETAILS_SUCCESS';
export const AGENT_PROFILE_DETAILS_FAIL = 'AGENT_PROFILE_DETAILS_FAIL';

export const AGENT_PASSWORD_UPDATE_REQUEST = 'AGENT_PASSWORD_UPDATE_REQUEST';
export const AGENT_PASSWORD_UPDATE_SUCCESS = 'AGENT_PASSWORD_UPDATE_SUCCESS';
export const AGENT_PASSWORD_UPDATE_FAIL = 'AGENT_PASSWORD_UPDATE_FAIL';

export const AGENT_REGISTER_REQUEST = "AGENT_REGISTER_REQUEST";
export const AGENT_REGISTER_SUCCESS = "AGENT_REGISTER_SUCCESS";
export const AGENT_REGISTER_FAIL = "AGENT_REGISTER_FAIL";
