export const APPLICATIONROLE_LIST_REQUEST = "APPLICATIONROLE_LIST_REQUEST"
export const APPLICATIONROLE_LIST_SUCCESS = "APPLICATIONROLE_LIST_SUCCESS"
export const APPLICATIONROLE_LIST_FAIL = "APPLICATIONROLE_LIST_FAIL"

export const APPLICATIONROLE_DETAILS_REQUEST = "APPLICATIONROLE_DETAILS_REQUEST"
export const APPLICATIONROLE_DETAILS_SUCCESS = "APPLICATIONROLE_DETAILS_SUCCESS"
export const APPLICATIONROLE_DETAILS_FAIL = "APPLICATIONROLE_DETAILS_FAIL"

export const APPLICATIONROLE_SAVE_REQUEST = "APPLICATIONROLE_SAVE_REQUEST";
export const APPLICATIONROLE_SAVE_SUCCESS = "APPLICATIONROLE_SAVE_SUCCESS";
export const APPLICATIONROLE_SAVE_FAIL = "APPLICATIONROLE_SAVE_FAIL";

export const APPLICATIONROLE_UPDATE_REQUEST = "APPLICATIONROLE_UPDATE_REQUEST";
export const APPLICATIONROLE_UPDATE_SUCCESS = "APPLICATIONROLE_UPDATE_SUCCESS";
export const APPLICATIONROLE_UPDATE_FAIL = "APPLICATIONROLE_UPDATE_FAIL";

export const APPLICATIONROLE_DELETE_REQUEST = "APPLICATIONROLE_DELETE_REQUEST";
export const APPLICATIONROLE_DELETE_SUCCESS = "APPLICATIONROLE_DELETE_SUCCESS";
export const APPLICATIONROLE_DELETE_FAIL = "APPLICATIONROLE_DELETE_FAIL";


