export const APPSHARER_PROFILE_UPDATE_REQUEST = "APPSHARER_PROFILE_UPDATE_REQUEST";
export const APPSHARER_PROFILE_UPDATE_SUCCESS = "APPSHARER_PROFILE_UPDATE_SUCCESS";
export const APPSHARER_PROFILE_UPDATE_FAIL = "APPSHARER_PROFILE_UPDATE_FAIL";

export const APPSHARER_PROFILE_DETAILS_REQUEST = "APPSHARER_PROFILE_DETAILS_REQUEST";
export const APPSHARER_PROFILE_DETAILS_SUCCESS = "APPSHARER_PROFILE_DETAILS_SUCCESS";
export const APPSHARER_PROFILE_DETAILS_FAIL = "APPSHARER_PROFILE_DETAILS_FAIL";

export const APPSHARER_PASSWORD_UPDATE_REQUEST = "APPSHARER_PASSWORD_UPDATE_REQUEST";
export const APPSHARER_PASSWORD_UPDATE_SUCCESS = "APPSHARER_PASSWORD_UPDATE_SUCCESS";
export const APPSHARER_PASSWORD_UPDATE_FAIL = "APPSHARER_PASSWORD_UPDATE_FAIL";

export const APPSHARER_REGISTER_REQUEST = "APPSHARER_REGISTER_REQUEST";
export const APPSHARER_REGISTER_SUCCESS = "APPSHARER_REGISTER_SUCCESS";
export const APPSHARER_REGISTER_FAIL = "APPSHARER_REGISTER_FAIL";

export const APPSHARER_DOWNLINE_LIST_REQUEST = "APPSHARER_DOWNLINE_LIST_REQUEST";
export const APPSHARER_DOWNLINE_LIST_SUCCESS = "APPSHARER_DOWNLINE_LIST_SUCCESS";
export const APPSHARER_DOWNLINE_LIST_FAIL = "APPSHARER_DOWNLINE_LIST_FAIL";
