export const CEO_LIST_REQUEST = "CEO_LIST_REQUEST"
export const CEO_LIST_SUCCESS = "CEO_LIST_SUCCESS"
export const CEO_LIST_FAIL = "CEO_LIST_FAIL"

export const CEO_PROFILE_UPDATE_REQUEST = "CEO_PROFILE_UPDATE_REQUEST";
export const CEO_PROFILE_UPDATE_SUCCESS = "CEO_PROFILE_UPDATE_SUCCESS";
export const CEO_PROFILE_UPDATE_FAIL = "CEO_PROFILE_UPDATE_FAIL";

export const CEO_PROFILE_DETAILS_REQUEST = 'CEO_PROFILE_DETAILS_REQUEST';
export const CEO_PROFILE_DETAILS_SUCCESS = 'CEO_PROFILE_DETAILS_SUCCESS';
export const CEO_PROFILE_DETAILS_FAIL = 'CEO_PROFILE_DETAILS_FAIL';

export const CEO_PASSWORD_UPDATE_REQUEST = 'CEO_PASSWORD_UPDATE_REQUEST';
export const CEO_PASSWORD_UPDATE_SUCCESS = 'CEO_PASSWORD_UPDATE_SUCCESS';
export const CEO_PASSWORD_UPDATE_FAIL = 'CEO_PASSWORD_UPDATE_FAIL';

export const CEO_REGISTER_REQUEST = "CEO_REGISTER_REQUEST";
export const CEO_REGISTER_SUCCESS = "CEO_REGISTER_SUCCESS";
export const CEO_REGISTER_FAIL = "CEO_REGISTER_FAIL";
