export const KARROT_LIST_REQUEST = "KARROT_LIST_REQUEST"
export const KARROT_LIST_SUCCESS = "KARROT_LIST_SUCCESS"
export const KARROT_LIST_FAIL = "KARROT_LIST_FAIL"

export const KARROT_PROFILE_UPDATE_REQUEST = "KARROT_PROFILE_UPDATE_REQUEST";
export const KARROT_PROFILE_UPDATE_SUCCESS = "KARROT_PROFILE_UPDATE_SUCCESS";
export const KARROT_PROFILE_UPDATE_FAIL = "KARROT_PROFILE_UPDATE_FAIL";

export const KARROT_PROFILE_DETAILS_REQUEST = 'KARROT_PROFILE_DETAILS_REQUEST';
export const KARROT_PROFILE_DETAILS_SUCCESS = 'KARROT_PROFILE_DETAILS_SUCCESS';
export const KARROT_PROFILE_DETAILS_FAIL = 'KARROT_PROFILE_DETAILS_FAIL';

export const KARROT_PASSWORD_UPDATE_REQUEST = 'KARROT_PASSWORD_UPDATE_REQUEST';
export const KARROT_PASSWORD_UPDATE_SUCCESS = 'KARROT_PASSWORD_UPDATE_SUCCESS';
export const KARROT_PASSWORD_UPDATE_FAIL = 'KARROT_PASSWORD_UPDATE_FAIL';

export const KARROT_REGISTER_REQUEST = "KARROT_REGISTER_REQUEST";
export const KARROT_REGISTER_SUCCESS = "KARROT_REGISTER_SUCCESS";
export const KARROT_REGISTER_FAIL = "KARROT_REGISTER_FAIL";
