export const MODERATOR_UPDATE_REQUEST = "MODERATOR_UPDATE_REQUEST";
export const MODERATOR_UPDATE_SUCCESS = "MODERATOR_UPDATE_SUCCESS";
export const MODERATOR_UPDATE_FAIL = "MODERATOR_UPDATE_FAIL";

export const MODERATOR_ADD_REQUEST = "MODERATOR_ADD_REQUEST";
export const MODERATOR_ADD_SUCCESS = "MODERATOR_ADD_SUCCESS";
export const MODERATOR_ADD_FAIL = "MODERATOR_ADD_FAIL";

export const MODERATOR_PROFILE_DETAILS_REQUEST = "MODERATOR_PROFILE_DETAILS_REQUEST";
export const MODERATOR_PROFILE_DETAILS_SUCCESS = "MODERATOR_PROFILE_DETAILS_SUCCESS";
export const MODERATOR_PROFILE_DETAILS_FAIL = "MODERATOR_PROFILE_DETAILS_FAIL";

export const MODERATOR_PASSWORD_UPDATE_REQUEST = "MODERATOR_PASSWORD_UPDATE_REQUEST";
export const MODERATOR_PASSWORD_UPDATE_SUCCESS = "MODERATOR_PASSWORD_UPDATE_SUCCESS";
export const MODERATOR_PASSWORD_UPDATE_FAIL = "MODERATOR_PASSWORD_UPDATE_FAIL";

export const MODERATOR_DELETE_REQUEST = "MODERATOR_DELETE_REQUEST";
export const MODERATOR_DELETE_SUCCESS = "MODERATOR_DELETE_SUCCESS";
export const MODERATOR_DELETE_FAIL = "MODERATOR_DELETE_FAIL";
