export const OFARZ_LIST_REQUEST = "OFARZ_LIST_REQUEST"
export const OFARZ_LIST_SUCCESS = "OFARZ_LIST_SUCCESS"
export const OFARZ_LIST_FAIL = "OFARZ_LIST_FAIL"

export const OFARZ_PASSWORD_UPDATE_REQUEST = 'OFARZ_PASSWORD_UPDATE_REQUEST';
export const OFARZ_PASSWORD_UPDATE_SUCCESS = 'OFARZ_PASSWORD_UPDATE_SUCCESS';
export const OFARZ_PASSWORD_UPDATE_FAIL = 'OFARZ_PASSWORD_UPDATE_FAIL';

export const OFARZ_REGISTER_REQUEST = "OFARZ_REGISTER_REQUEST";
export const OFARZ_REGISTER_SUCCESS = "OFARZ_REGISTER_SUCCESS";
export const OFARZ_REGISTER_FAIL = "OFARZ_REGISTER_FAIL";
