export const SHOPER_REGISTER_REQUEST = "SHOPER_REGISTER_REQUEST";
export const SHOPER_REGISTER_SUCCESS = "SHOPER_REGISTER_SUCCESS";
export const SHOPER_REGISTER_FAIL = "SHOPER_REGISTER_FAIL";

export const SHOPER_PASSWORD_UPDATE_REQUEST = 'SHOPER_PASSWORD_UPDATE_REQUEST';
export const SHOPER_PASSWORD_UPDATE_SUCCESS = 'SHOPER_PASSWORD_UPDATE_SUCCESS';
export const SHOPER_PASSWORD_UPDATE_FAIL = 'SHOPER_PASSWORD_UPDATE_FAIL';

export const SHOPER_DELETE_REQUEST = "SHOPER_DELETE_REQUEST";
export const SHOPER_DELETE_SUCCESS = "SHOPER_DELETE_SUCCESS";
export const SHOPER_DELETE_FAIL = "SHOPER_DELETE_FAIL";

