export const COUNTRY_LIST_REQUEST = "COUNTRY_LIST_REQUEST"
export const COUNTRY_LIST_SUCCESS = "COUNTRY_LIST_SUCCESS"
export const COUNTRY_LIST_FAIL = "COUNTRY_LIST_FAIL"


export const DIVISION_LIST_REQUEST = "DIVISION_LIST_REQUEST"
export const DIVISION_LIST_SUCCESS = "DIVISION_LIST_SUCCESS"
export const DIVISION_LIST_FAIL = "DIVISION_LIST_FAIL"


export const DISTRICT_LIST_REQUEST = "DISTRICT_LIST_REQUEST"
export const DISTRICT_LIST_SUCCESS = "DISTRICT_LIST_SUCCESS"
export const DISTRICT_LIST_FAIL = "DISTRICT_LIST_FAIL"


export const UPOZILA_LIST_REQUEST = "UPOZILA_LIST_REQUEST";
export const UPOZILA_LIST_SUCCESS = "UPOZILA_LIST_SUCCESS";
export const UPOZILA_LIST_FAIL = "UPOZILA_LIST_FAIL";


export const UNION_LIST_REQUEST = "UNION_LIST_REQUEST"
export const UNION_LIST_SUCCESS = "UNION_LIST_SUCCESS"
export const UNION_LIST_FAIL = "UNION_LIST_FAIL"


export const MARKET_LIST_REQUEST = "MARKET_LIST_REQUEST"
export const MARKET_LIST_SUCCESS = "MARKET_LIST_SUCCESS"
export const MARKET_LIST_FAIL = "MARKET_LIST_FAIL"


export const AREA_CODE_LIST_REQUEST = "AREA_CODE_LIST_REQUEST"
export const AREA_CODE_LIST_SUCCESS = "AREA_CODE_LIST_SUCCESS"
export const AREA_CODE_LIST_FAIL = "AREA_CODE_LIST_FAIL"