export const DIVISION_LIST_REQUEST = "DIVISION_LIST_REQUEST"
export const DIVISION_LIST_SUCCESS = "DIVISION_LIST_SUCCESS"
export const DIVISION_LIST_FAIL = "DIVISION_LIST_FAIL"

export const DIVISION_DETAILS_REQUEST = "DIVISION_DETAILS_REQUEST"
export const DIVISION_DETAILS_SUCCESS = "DIVISION_DETAILS_SUCCESS"
export const DIVISION_DETAILS_FAIL = "DIVISION_DETAILS_FAIL"

export const DIVISION_SAVE_REQUEST = "DIVISION_SAVE_REQUEST";
export const DIVISION_SAVE_SUCCESS = "DIVISION_SAVE_SUCCESS";
export const DIVISION_SAVE_FAIL = "DIVISION_SAVE_FAIL";

export const DIVISION_UPDATE_REQUEST = "DIVISION_UPDATE_REQUEST";
export const DIVISION_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const DIVISION_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";

export const DIVISION_DELETE_REQUEST = "DIVISION_DELETE_REQUEST";
export const DIVISION_DELETE_SUCCESS = "DIVISION_DELETE_SUCCESS";
export const DIVISION_DELETE_FAIL = "DIVISION_DELETE_FAIL";