export const MARKET_LIST_REQUEST = "MARKET_LIST_REQUEST"
export const MARKET_LIST_SUCCESS = "MARKET_LIST_SUCCESS"
export const MARKET_LIST_FAIL = "MARKET_LIST_FAIL"

export const MARKET_DETAILS_REQUEST = "MARKET_DETAILS_REQUEST"
export const MARKET_DETAILS_SUCCESS = "MARKET_DETAILS_SUCCESS"
export const MARKET_DETAILS_FAIL = "MARKET_DETAILS_FAIL"

export const MARKET_SAVE_REQUEST = "MARKET_SAVE_REQUEST";
export const MARKET_SAVE_SUCCESS = "MARKET_SAVE_SUCCESS";
export const MARKET_SAVE_FAIL = "MARKET_SAVE_FAIL";

export const MARKET_UPDATE_REQUEST = "MARKET_UPDATE_REQUEST";
export const MARKET_UPDATE_SUCCESS = "MARKET_UPDATE_SUCCESS";
export const MARKET_UPDATE_FAIL = "MARKET_UPDATE_FAIL";

export const MARKET_DELETE_REQUEST = "MARKET_DELETE_REQUEST";
export const MARKET_DELETE_SUCCESS = "MARKET_DELETE_SUCCESS";
export const MARKET_DELETE_FAIL = "MARKET_DELETE_FAIL";