export const UNION_LIST_REQUEST = "UNION_LIST_REQUEST"
export const UNION_LIST_SUCCESS = "UNION_LIST_SUCCESS"
export const UNION_LIST_FAIL = "UNION_LIST_FAIL"

export const UNION_DETAILS_REQUEST = "UNION_DETAILS_REQUEST"
export const UNION_DETAILS_SUCCESS = "UNION_DETAILS_SUCCESS"
export const UNION_DETAILS_FAIL = "UNION_DETAILS_FAIL"

export const UNION_SAVE_REQUEST = "UNION_SAVE_REQUEST";
export const UNION_SAVE_SUCCESS = "UNION_SAVE_SUCCESS";
export const UNION_SAVE_FAIL = "UNION_SAVE_FAIL";

export const UNION_UPDATE_REQUEST = "UNION_UPDATE_REQUEST";
export const UNION_UPDATE_SUCCESS = "UNION_UPDATE_SUCCESS";
export const UNION_UPDATE_FAIL = "UNION_UPDATE_FAIL";

export const UNION_DELETE_REQUEST = "UNION_DELETE_REQUEST";
export const UNION_DELETE_SUCCESS = "UNION_DELETE_SUCCESS";
export const UNION_DELETE_FAIL = "UNION_DELETE_FAIL";