export const UPOZILA_LIST_REQUEST = "UPOZILA_LIST_REQUEST";
export const UPOZILA_LIST_SUCCESS = "UPOZILA_LIST_SUCCESS";
export const UPOZILA_LIST_FAIL = "UPOZILA_LIST_FAIL";

export const UPOZILA_DETAILS_REQUEST = "UPOZILA_DETAILS_REQUEST";
export const UPOZILA_DETAILS_SUCCESS = "UPOZILA_DETAILS_SUCCESS";
export const UPOZILA_DETAILS_FAIL = "UPOZILA_DETAILS_FAIL";

export const UPOZILA_SAVE_REQUEST = "UPOZILA_SAVE_REQUEST";
export const UPOZILA_SAVE_SUCCESS = "UPOZILA_SAVE_SUCCESS";
export const UPOZILA_SAVE_FAIL = "UPOZILA_SAVE_FAIL";

export const UPOZILA_UPDATE_REQUEST = "UPOZILA_UPDATE_REQUEST";
export const UPOZILA_UPDATE_SUCCESS = "UPOZILA_UPDATE_SUCCESS";
export const UPOZILA_UPDATE_FAIL = "UPOZILA_UPDATE_FAIL";

export const UPOZILA_DELETE_REQUEST = "UPOZILA_DELETE_REQUEST";
export const UPOZILA_DELETE_SUCCESS = "UPOZILA_DELETE_SUCCESS";
export const UPOZILA_DELETE_FAIL = "UPOZILA_DELETE_FAIL";