export const FUND_LIST_REQUEST_AGENT = "FUND_LIST_REQUEST_AGENT"
export const FUND_LIST_SUCCESS_AGENT = "FUND_LIST_SUCCESS_AGENT"
export const FUND_LIST_FAIL_AGENT = "FUND_LIST_FAIL_AGENT"

export const FUND_REQUEST_AGENT = "FUND_REQUEST_AGENT"
export const FUND_SUCCESS_AGENT = "FUND_SUCCESS_AGENT"
export const FUND_FAIL_AGENT = "FUND_FAIL_AGENT"




export const FUND_LIST_REQUEST_APPSHARER = "FUND_LIST_REQUEST_APPSHARER"
export const FUND_LIST_SUCCESS_APPSHARER = "FUND_LIST_SUCCESS_APPSHARER"
export const FUND_LIST_FAIL_APPSHARER = "FUND_LIST_FAIL_APPSHARER"

export const FUND_REQUEST_APPSHARER = "FUND_REQUEST_APPSHARER"
export const FUND_SUCCESS_APPSHARER = "FUND_SUCCESS_APPSHARER"
export const FUND_FAIL_APPSHARER = "FUND_FAIL_APPSHARER"




export const FUND_LIST_REQUEST_SHOPER = "FUND_LIST_REQUEST_SHOPER"
export const FUND_LIST_SUCCESS_SHOPER = "FUND_LIST_SUCCESS_SHOPER"
export const FUND_LIST_FAIL_SHOPER = "FUND_LIST_FAIL_SHOPER"

export const FUND_REQUEST_SHOPER = "FUND_REQUEST_SHOPER"
export const FUND_SUCCESS_SHOPER = "FUND_SUCCESS_SHOPER"
export const FUND_FAIL_SHOPER = "FUND_FAIL_SHOPER"




export const FUND_LIST_REQUEST_KARROT = "FUND_LIST_REQUEST_KARROT"
export const FUND_LIST_SUCCESS_KARROT = "FUND_LIST_SUCCESS_KARROT"
export const FUND_LIST_FAIL_KARROT = "FUND_LIST_FAIL_KARROT"

export const FUND_REQUEST_KARROT = "FUND_REQUEST_KARROT"
export const FUND_SUCCESS_KARROT = "FUND_SUCCESS_KARROT"
export const FUND_FAIL_KARROT = "FUND_FAIL_KARROT"




export const FUND_LIST_REQUEST_CEO = "FUND_LIST_REQUEST_CEO"
export const FUND_LIST_SUCCESS_CEO = "FUND_LIST_SUCCESS_CEO"
export const FUND_LIST_FAIL_CEO = "FUND_LIST_FAIL_CEO"

export const FUND_REQUEST_CEO = "FUND_REQUEST_CEO"
export const FUND_SUCCESS_CEO = "FUND_SUCCESS_CEO"
export const FUND_FAIL_CEO = "FUND_FAIL_CEO"





export const FUND_LIST_REQUEST_OFARZ = "FUND_LIST_REQUEST_OFARZ"
export const FUND_LIST_SUCCESS_OFARZ = "FUND_LIST_SUCCESS_OFARZ"
export const FUND_LIST_FAIL_OFARZ = "FUND_LIST_FAIL_OFARZ"


export const FUND_REQUEST_OFARZ = "FUND_REQUEST_OFARZ"
export const FUND_SUCCESS_OFARZ = "FUND_SUCCESS_OFARZ"
export const FUND_FAIL_OFARZ = "FUND_FAIL_OFARZ"

