export const PAYMENTTYPE_LIST_REQUEST = "PAYMENTTYPE_LIST_REQUEST"
export const PAYMENTTYPE_LIST_SUCCESS = "PAYMENTTYPE_LIST_SUCCESS"
export const PAYMENTTYPE_LIST_FAIL = "PAYMENTTYPE_LIST_FAIL"

export const PAYMENTTYPE_DETAILS_REQUEST = "PAYMENTTYPE_DETAILS_REQUEST"
export const PAYMENTTYPE_DETAILS_SUCCESS = "PAYMENTTYPE_DETAILS_SUCCESS"
export const PAYMENTTYPE_DETAILS_FAIL = "PAYMENTTYPE_DETAILS_FAIL"

export const PAYMENTTYPE_SAVE_REQUEST = "PAYMENTTYPE_SAVE_REQUEST";
export const PAYMENTTYPE_SAVE_SUCCESS = "PAYMENTTYPE_SAVE_SUCCESS";
export const PAYMENTTYPE_SAVE_FAIL = "PAYMENTTYPE_SAVE_FAIL";

export const PAYMENTTYPE_UPDATE_REQUEST = "PAYMENTTYPE_UPDATE_REQUEST";
export const PAYMENTTYPE_UPDATE_SUCCESS = "PAYMENTTYPE_UPDATE_SUCCESS";
export const PAYMENTTYPE_UPDATE_FAIL = "PAYMENTTYPE_UPDATE_FAIL";

export const PAYMENTTYPE_DELETE_REQUEST = "PAYMENTTYPE_DELETE_REQUEST";
export const PAYMENTTYPE_DELETE_SUCCESS = "PAYMENTTYPE_DELETE_SUCCESS";
export const PAYMENTTYPE_DELETE_FAIL = "PAYMENTTYPE_DELETE_FAIL";