export const WITHDRAW_LIST_REQUEST = "WITHDRAW_LIST_REQUEST"
export const WITHDRAW_LIST_SUCCESS = "WITHDRAW_LIST_SUCCESS"
export const WITHDRAW_LIST_FAIL = "WITHDRAW_LIST_FAIL"

//#region Agent

export const WITHDRAW_LIST_REQUEST_AGENT_TO_OFARZ = "WITHDRAW_LIST_REQUEST_AGENT_TO_OFARZ"
export const WITHDRAW_LIST_SUCCESS_AGENT_TO_OFARZ = "WITHDRAW_LIST_SUCCESS_AGENT_TO_OFARZ"
export const WITHDRAW_LIST_FAIL_AGENT_TO_OFARZ = "WITHDRAW_LIST_FAIL_AGENT_TO_OFARZ"


export const WITHDRAW_REQUEST_AGENT_TO_OFARZ = "WITHDRAW_REQUEST_AGENT_TO_OFARZ"
export const WITHDRAW_SUCCESS_AGENT_TO_OFARZ = "WITHDRAW_SUCCESS_AGENT_TO_OFARZ"
export const WITHDRAW_FAIL_AGENT_TO_OFARZ = "WITHDRAW_FAIL_AGENT_TO_OFARZ"


export const WITHDRAW_LIST_REQUEST_AGENT_FROM_USER = "WITHDRAW_LIST_REQUEST_AGENT_FROM_USER"
export const WITHDRAW_LIST_SUCCESS_AGENT_FROM_USER = "WITHDRAW_LIST_SUCCESS_AGENT_FROM_USER"
export const WITHDRAW_LIST_FAIL_AGENT_FROM_USER = "WITHDRAW_LIST_FAIL_AGENT_FROM_USER"

//#endregion

//#region App Sharer

export const WITHDRAW_LIST_REQUEST_APPSHARER_TO_AGENT = "WITHDRAW_LIST_REQUEST_APPSHARER_TO_AGENT"
export const WITHDRAW_LIST_SUCCESS_APPSHARER_TO_AGENT = "WITHDRAW_LIST_SUCCESS_APPSHARER_TO_AGENT"
export const WITHDRAW_LIST_FAIL_APPSHARER_TO_AGENT = "WITHDRAW_LIST_FAIL_APPSHARER_TO_AGENT"

export const WITHDRAW_LIST_REQUEST_APPSHARER_TO_OFARZ = "WITHDRAW_LIST_REQUEST_APPSHARER_TO_OFARZ"
export const WITHDRAW_LIST_SUCCESS_APPSHARER_TO_OFARZ = "WITHDRAW_LIST_SUCCESS_APPSHARER_TO_OFARZ"
export const WITHDRAW_LIST_FAIL_APPSHARER_TO_OFARZ = "WITHDRAW_LIST_FAIL_APPSHARER_TO_OFARZ"

export const WITHDRAW_REQUEST_APPSHARER_TO_AGENT = "WITHDRAW_REQUEST_APPSHARER_TO_AGENT"
export const WITHDRAW_SUCCESS_APPSHARER_TO_AGENT = "WITHDRAW_SUCCESS_APPSHARER_TO_AGENT"
export const WITHDRAW_FAIL_APPSHARER_TO_AGENT = "WITHDRAW_FAIL_APPSHARER_TO_AGENT"

export const WITHDRAW_REQUEST_APPSHARER_TO_OFARZ = "WITHDRAW_REQUEST_APPSHARER_TO_OFARZ"
export const WITHDRAW_SUCCESS_APPSHARER_TO_OFARZ = "WITHDRAW_SUCCESS_APPSHARER_TO_OFARZ"
export const WITHDRAW_FAIL_APPSHARER_TO_OFARZ = "WITHDRAW_FAIL_APPSHARER_TO_OFARZ"
//#endregion

//#region Karrot
export const WITHDRAW_LIST_REQUEST_KARROT_TO_OFARZ = "WITHDRAW_LIST_REQUEST_KARROT_TO_OFARZ"
export const WITHDRAW_LIST_SUCCESS_KARROT_TO_OFARZ = "WITHDRAW_LIST_SUCCESS_KARROT_TO_OFARZ"
export const WITHDRAW_LIST_FAIL_KARROT_TO_OFARZ = "WITHDRAW_LIST_FAIL_KARROT_TO_OFARZ"

export const WITHDRAW_LIST_REQUEST_KARROT_TO_AGENT = "WITHDRAW_LIST_REQUEST_KARROT_TO_AGENT"
export const WITHDRAW_LIST_SUCCESS_KARROT_TO_AGENT = "WITHDRAW_LIST_SUCCESS_KARROT_TO_AGENT"
export const WITHDRAW_LIST_FAIL_KARROT_TO_AGENT = "WITHDRAW_LIST_FAIL_KARROT_TO_AGENT"

export const WITHDRAW_REQUEST_KARROT_TO_OFARZ = "WITHDRAW_REQUEST_KARROT_TO_OFARZ"
export const WITHDRAW_SUCCESS_KARROT_TO_OFARZ = "WITHDRAW_SUCCESS_KARROT_TO_OFARZ"
export const WITHDRAW_FAIL_KARROT_TO_OFARZ = "WITHDRAW_FAIL_KARROT_TO_OFARZ"

export const WITHDRAW_REQUEST_KARROT_TO_AGENT = "WITHDRAW_REQUEST_KARROT_TO_AGENT"
export const WITHDRAW_SUCCESS_KARROT_TO_AGENT = "WITHDRAW_SUCCESS_KARROT_TO_AGENT"
export const WITHDRAW_FAIL_KARROT_TO_AGENT = "WITHDRAW_FAIL_KARROT_TO_AGENT"
//#endregion

//#region CEO
export const WITHDRAW_LIST_REQUEST_CEO_TO_OFARZ = "WITHDRAW_LIST_REQUEST_CEO_TO_OFARZ"
export const WITHDRAW_LIST_SUCCESS_CEO_TO_OFARZ = "WITHDRAW_LIST_SUCCESS_CEO_TO_OFARZ"
export const WITHDRAW_LIST_FAIL_CEO_TO_OFARZ = "WITHDRAW_LIST_FAIL_CEO_TO_OFARZ"

export const WITHDRAW_LIST_REQUEST_CEO_TO_AGENT = "WITHDRAW_LIST_REQUEST_CEO_TO_AGENT"
export const WITHDRAW_LIST_SUCCESS_CEO_TO_AGENT = "WITHDRAW_LIST_SUCCESS_CEO_TO_AGENT"
export const WITHDRAW_LIST_FAIL_CEO_TO_AGENT = "WITHDRAW_LIST_FAIL_CEO_TO_AGENT"

export const WITHDRAW_REQUEST_CEO_TO_OFARZ = "WITHDRAW_REQUEST_CEO_TO_OFARZ"
export const WITHDRAW_SUCCESS_CEO_TO_OFARZ = "WITHDRAW_SUCCESS_CEO_TO_OFARZ"
export const WITHDRAW_FAIL_CEO_TO_OFARZ = "WITHDRAW_FAIL_CEO_TO_OFARZ"

export const WITHDRAW_REQUEST_CEO_TO_AGENT = "WITHDRAW_REQUEST_CEO_TO_AGENT"
export const WITHDRAW_SUCCESS_CEO_TO_AGENT = "WITHDRAW_SUCCESS_CEO_TO_AGENT"
export const WITHDRAW_FAIL_CEO_TO_AGENT = "WITHDRAW_FAIL_CEO_TO_AGENT"
//#endregion




//#region Ofarz
export const WITHDRAW_LIST_REQUEST_OFARZ_FROM_APPSHARER = "WITHDRAW_LIST_REQUEST_OFARZ_FROM_APPSHARER"
export const WITHDRAW_LIST_SUCCESS_OFARZ_FROM_APPSHARER = "WITHDRAW_LIST_SUCCESS_OFARZ_FROM_APPSHARER"
export const WITHDRAW_LIST_FAIL_OFARZ_FROM_APPSHARER = "WITHDRAW_LIST_FAIL_OFARZ_FROM_APPSHARER"

export const WITHDRAW_LIST_REQUEST_OFARZ_FROM_KARROT = "WITHDRAW_LIST_REQUEST_OFARZ_FROM_KARROT"
export const WITHDRAW_LIST_SUCCESS_OFARZ_FROM_KARROT = "WITHDRAW_LIST_SUCCESS_OFARZ_FROM_KARROT"
export const WITHDRAW_LIST_FAIL_OFARZ_FROM_KARROT = "WITHDRAW_LIST_FAIL_OFARZ_FROM_KARROT"

export const WITHDRAW_LIST_REQUEST_OFARZ_FROM_CEO = "WITHDRAW_LIST_REQUEST_OFARZ_FROM_CEO"
export const WITHDRAW_LIST_SUCCESS_OFARZ_FROM_CEO = "WITHDRAW_LIST_SUCCESS_OFARZ_FROM_CEO"
export const WITHDRAW_LIST_FAIL_OFARZ_FROM_CEO = "WITHDRAW_LIST_FAIL_OFARZ_FROM_CEO"
//#endregion


